In [1]:
%matplotlib inline
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# File to Load
crime_data = "crime_data.csv"

# Read the crime_data
crime_df = pd.read_csv(crime_data)
crime_df.head()

/Users/fernandawolburg/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,INC NUMBER,OCCURRED ON,OCCURRED TO,UCR CRIME CATEGORY,100 BLOCK ADDR,ZIP,PREMISE TYPE
0,201600000052855,11/01/2015 00:00,01/09/2016 00:00,MOTOR VEHICLE THEFT,N 43RD AVE & W CACTUS RD,85029.0,SINGLE FAMILY HOUSE
1,201600000594484,11/01/2015 00:00,NaN,RAPE,13XX E ALMERIA RD,85006.0,SINGLE FAMILY HOUSE
2,201500002102327,11/01/2015 00:00,11/01/2015 09:00,LARCENY-THEFT,51XX N 15TH ST,85014.0,APARTMENT
3,201500002101405,11/01/2015 00:00,11/01/2015 05:00,MOTOR VEHICLE THEFT,102XX W MEDLOCK AVE,85307.0,SINGLE FAMILY HOUSE
4,201500002102668,11/01/2015 00:00,11/01/2015 11:50,MOTOR VEHICLE THEFT,69XX W WOOD ST,85043.0,SINGLE FAMILY HOUSE

In [7]:
# create new data frame with the columns that will be helpful for the project: 
#inc number, occurred on, UCR crime cateogry, and premise type
new_crime_df = pd.DataFrame({'INC NUMBER': crime_df['INC NUMBER'],
                'OCCURRED ON': crime_df['OCCURRED ON'],
                'UCR CRIME CATEGORY': crime_df['UCR CRIME CATEGORY'],
                'PREMISE TYPE': crime_df['PREMISE TYPE']})
new_crime_df.head()

,INC NUMBER,OCCURRED ON,UCR CRIME CATEGORY,PREMISE TYPE
0,201600000052855,11/01/2015 00:00,MOTOR VEHICLE THEFT,SINGLE FAMILY HOUSE
1,201600000594484,11/01/2015 00:00,RAPE,SINGLE FAMILY HOUSE
2,201500002102327,11/01/2015 00:00,LARCENY-THEFT,APARTMENT
3,201500002101405,11/01/2015 00:00,MOTOR VEHICLE THEFT,SINGLE FAMILY HOUSE
4,201500002102668,11/01/2015 00:00,MOTOR VEHICLE THEFT,SINGLE FAMILY HOUSE

In [8]:
# Take out the time from the "OCCURRED ON" column so you can group data by day
new_crime_df['OCCURRED ON'] = new_crime_df['OCCURRED ON'].map(lambda x: str(x)[:-6])
new_crime_df['OCCURRED ON']

0         11/01/2015
1         11/01/2015
2         11/01/2015
3         11/01/2015
4         11/01/2015
5         11/01/2015
6         11/01/2015
7         11/01/2015
8         11/01/2015
9         11/01/2015
10        11/01/2015
11        11/01/2015
12        11/01/2015
13        11/01/2015
14        11/01/2015
15        11/01/2015
16        11/01/2015
17        11/01/2015
18        11/01/2015
19        11/01/2015
20        11/01/2015
21        11/01/2015
22        11/01/2015
23        11/01/2015
24        11/01/2015
25        11/01/2015
26        11/01/2015
27        11/01/2015
28        11/01/2015
29        11/01/2015
             ...
239047    07/05/2019
239048    07/05/2019
239049    07/05/2019
239050    07/05/2019
239051    07/05/2019
239052    07/05/2019
239053    07/05/2019
239054    07/05/2019
239055    07/05/2019
239056    07/05/2019
239057    07/05/2019
239058    07/05/2019
239059    07/05/2019
239060    07/05/2019
239061    07/05/2019
239062    07/05/2019
239063    07/05/2019
239064    07/05/2019
239065    07/05/2019
239066    07/05/2019
239067    07/05/2019
239068    07/05/2019
239069    07/05/2019
239070    07/05/2019
239071    07/05/2019
239072    07/05/2019
239073    07/05/2019
239074    07/05/2019
239075    07/05/2019
239076    07/05/2019
Name: OCCURRED ON, Length: 239077, dtype: object

In [9]:
# drop rows that don't have a value
new_crime_df.dropna()

,INC NUMBER,OCCURRED ON,UCR CRIME CATEGORY,PREMISE TYPE
0,201600000052855,11/01/2015,MOTOR VEHICLE THEFT,SINGLE FAMILY HOUSE
1,201600000594484,11/01/2015,RAPE,SINGLE FAMILY HOUSE
2,201500002102327,11/01/2015,LARCENY-THEFT,APARTMENT
3,201500002101405,11/01/2015,MOTOR VEHICLE THEFT,SINGLE FAMILY HOUSE
4,201500002102668,11/01/2015,MOTOR VEHICLE THEFT,SINGLE FAMILY HOUSE
5,201600000527709,11/01/2015,LARCENY-THEFT,PARKING LOT
6,201700001722914,11/01/2015,LARCENY-THEFT,SINGLE FAMILY HOUSE
7,201700001603695,11/01/2015,RAPE,HOSPITAL
8,201500002168686,11/01/2015,LARCENY-THEFT,PARKING LOT
9,201500002103724,11/01/2015,DRUG OFFENSE,APARTMENT
10,201500002102467,11/01/2015,LARCENY-THEFT,VEHICLE
11,201600000090387,11/01/2015,LARCENY-THEFT,SINGLE FAMILY HOUSE
12,201500002147335,11/01/2015,LARCENY-THEFT,VEHICLE
13,201600000575804,11/01/2015,LARCENY-THEFT,SINGLE FAMILY HOUSE
14,201500002334281,11/01/2015,MOTOR VEHICLE THEFT,PARKING LOT
15,201500002391368,11/01/2015,LARCENY-THEFT,SINGLE FAMILY HOUSE
16,201500002371588,11/01/2015,LARCENY-THEFT,HOSPITAL
17,201600000623876,11/01/2015,LARCENY-THEFT,SINGLE FAMILY HOUSE
18,201500002102534,11/01/2015,BURGLARY,SINGLE FAMILY HOUSE
19,201600000042041,11/01/2015,MOTOR VEHICLE THEFT,CONDO / TOWNHOUSE
20,201500002102481,11/01/2015,LARCENY-THEFT,HOTEL / MOTEL
21,201500002326780,11/01/2015,BURGLARY,SINGLE FAMILY HOUSE
22,201600002077992,11/01/2015,LARCENY-THEFT,PARKING LOT
23,201600000223791,11/01/2015,BURGLARY,07A STOREROOM/SHED (COMMERCIAL)
24,201500002100158,11/01/2015,MOTOR VEHICLE THEFT,CONVENIENCE MARKET / STORE
25,201500002101675,11/01/2015,LARCENY-THEFT,DRIVEWAY
26,201500002103050,11/01/2015,LARCENY-THEFT,VEHICLE
27,201500002103663,11/01/2015,LARCENY-THEFT,SINGLE FAMILY HOUSE
28,201500002119698,11/01/2015,LARCENY-THEFT,SINGLE FAMILY HOUSE
29,201500002101758,11/01/2015,MOTOR VEHICLE THEFT,PARKING LOT
...,...,...,...,...
239047,201900001149223,07/05/2019,LARCENY-THEFT,CONVENIENCE MARKET / STORE
239048,201900001151667,07/05/2019,LARCENY-THEFT,VEHICLE
239049,201900001149453,07/05/2019,LARCENY-THEFT,RESTAURANT
239050,201900001149128,07/05/2019,LARCENY-THEFT,PARKING LOT
239051,201900001149256,07/05/2019,LARCENY-THEFT,GROCERY / SUPER MARKET
239052,201900001149296,07/05/2019,AGGRAVATED ASSAULT,PARKING LOT
239053,201900001151736,07/05/2019,BURGLARY,SPECIALTY STORE
239054,201900001149356,07/05/2019,LARCENY-THEFT,GROCERY / SUPER MARKET
239055,201900001149940,07/05/2019,RAPE,APARTMENT
239056,201900001149457,07/05/2019,DRUG OFFENSE,APARTMENT
239057,201900001151610,07/05/2019,MOTOR VEHICLE THEFT,STREET / ROADWAY / ALLEY / SIDEWALK
239058,201900001152136,07/05/2019,BURGLARY,SINGLE FAMILY HOUSE
239059,201900001149551,07/05/2019,LARCENY-THEFT,CONVENIENCE MARKET / STORE
239060,201900001150980,07/05/2019,ROBBERY,PARKING LOT
239061,201900001149660,07/05/2019,DRUG OFFENSE,VEHICLE
239062,201900001153666,07/05/2019,LARCENY-THEFT,STREET / ROADWAY / ALLEY / SIDEWALK
239063,201900001154114,07/05/2019,LARCENY-THEFT,PARKING LOT
239064,201900001167345,07/05/2019,RAPE,APARTMENT
239065,201900001154841,07/05/2019,LARCENY-THEFT,PARKING LOT
239066,201900001151829,07/05/2019,LARCENY-THEFT,PARKING LOT
239067,201900001168273,07/05/2019,LARCENY-THEFT,SINGLE FAMILY HOUSE
239068,201900001150021,07/05/2019,DRUG OFFENSE,STREET / ROADWAY / ALLEY / SIDEWALK
239069,201900001150887,07/05/2019,LARCENY-THEFT,PARKING LOT
239070,201900001150177,07/05/2019,LARCENY-THEFT,PARKING GARAGE
239071,201900001150238,07/05/2019,LARCENY-THEFT,DEPARTMENT / DISCOUNT STORE
239072,201900001150362,07/05/2019,ROBBERY,STREET / ROADWAY / ALLEY / SIDEWALK
239073,201900001152033,07/05/2019,LARCENY-THEFT,APARTMENT
239074,201900001150335,07/05/2019,AGGRAVATED ASSAULT,PARK / PLAYGROUND
239075,201900001150395,07/05/2019,LARCENY-THEFT,PARKING LOT
239076,201900001150404,07/05/2019,DRUG OFFENSE,APARTMENT

In [18]:
# Take out the time from the "OCCURRED ON" column so you can group data by day
#new_crime_df['YEAR'] = new_crime_df['OCCURRED ON'].map(lambda x: str(x)[6:])
new_crime_df.head()

,INC NUMBER,OCCURRED ON,UCR CRIME CATEGORY,PREMISE TYPE,YEAR
0,201600000052855,11/01/2015,MOTOR VEHICLE THEFT,SINGLE FAMILY HOUSE,2015
1,201600000594484,11/01/2015,RAPE,SINGLE FAMILY HOUSE,2015
2,201500002102327,11/01/2015,LARCENY-THEFT,APARTMENT,2015
3,201500002101405,11/01/2015,MOTOR VEHICLE THEFT,SINGLE FAMILY HOUSE,2015
4,201500002102668,11/01/2015,MOTOR VEHICLE THEFT,SINGLE FAMILY HOUSE,2015

In [13]:
crime_group = new_crime_df.groupby('OCCURRED ON')
crime_counts_day = crime_group['OCCURRED ON'].value_counts()
crime_counts_day
#plt.plot(new_crime_df['INC NUMBER'].value_counts(),)
#plt.show()

OCCURRED ON  OCCURRED ON
                            420
01/01/2016   01/01/2016     205
01/01/2017   01/01/2017     210
01/01/2018   01/01/2018     228
01/01/2019   01/01/2019     191
01/02/2016   01/02/2016     143
01/02/2017   01/02/2017     146
01/02/2018   01/02/2018     162
01/02/2019   01/02/2019     165
01/03/2016   01/03/2016     146
01/03/2017   01/03/2017     179
01/03/2018   01/03/2018     162
01/03/2019   01/03/2019     201
01/04/2016   01/04/2016     188
01/04/2017   01/04/2017     180
01/04/2018   01/04/2018     184
01/04/2019   01/04/2019     199
01/05/2016   01/05/2016     165
01/05/2017   01/05/2017     172
01/05/2018   01/05/2018     197
01/05/2019   01/05/2019     162
01/06/2016   01/06/2016     199
01/06/2017   01/06/2017     187
01/06/2018   01/06/2018     202
01/06/2019   01/06/2019     172
01/07/2016   01/07/2016     170
01/07/2017   01/07/2017     177
01/07/2018   01/07/2018     159
01/07/2019   01/07/2019     171
01/08/2016   01/08/2016     192
                           ...
12/24/2017   12/24/2017     147
12/24/2018   12/24/2018     166
12/25/2015   12/25/2015     120
12/25/2016   12/25/2016     108
12/25/2017   12/25/2017     130
12/25/2018   12/25/2018     122
12/26/2015   12/26/2015     145
12/26/2016   12/26/2016     154
12/26/2017   12/26/2017     142
12/26/2018   12/26/2018     139
12/27/2015   12/27/2015     144
12/27/2016   12/27/2016     188
12/27/2017   12/27/2017     143
12/27/2018   12/27/2018     144
12/28/2015   12/28/2015     170
12/28/2016   12/28/2016     182
12/28/2017   12/28/2017     177
12/28/2018   12/28/2018     169
12/29/2015   12/29/2015     168
12/29/2016   12/29/2016     192
12/29/2017   12/29/2017     167
12/29/2018   12/29/2018     169
12/30/2015   12/30/2015     157
12/30/2016   12/30/2016     177
12/30/2017   12/30/2017     146
12/30/2018   12/30/2018     151
12/31/2015   12/31/2015     186
12/31/2016   12/31/2016     175
12/31/2017   12/31/2017     173
12/31/2018   12/31/2018     179
Name: OCCURRED ON, Length: 1344, dtype: int64

In [21]:
# Loc on the year of each crime incident to match the crime calls
#crime_2016 = new_crime_df.loc[(crime_df["YEAR"] == "2016")]
#crime_2017 = new_crime_df.loc[(crime_df["YEAR"] == "2017")]
#crime_2018 = new_crime_df.loc[(crime_df["YEAR"] == "2018")]
# create a dataframe for 2016
#crime_2016 = pd.DataFrame({'INC NUMBER': new_crime_df['INC NUMBER'],
 #               'OCCURRED ON': new_crime_df['OCCURRED ON'],
  #              'UCR CRIME CATEGORY': new_crime_df['UCR CRIME CATEGORY'],
   #             'PREMISE TYPE': new_crime_df['PREMISE TYPE'],
    #            'YEAR': new_crime_df(new_crime_df['YEAR'] == 2016)})